config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin/crear_cuenta'
  get 'admin/reiniciar_cuenta'
  get 'admin/reset_password'
  post 'admin/setear_datos_del_alumno'
  post 'admin/actualizar_password'

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :examenes, :only => :index do
    get :shows, :on => :collection
  end

  resources :horarios, :only => :index do
    get :shows, :on => :collection
  end
  
  resources :historiales, :only => :index do
    get :shows, :on => :collection
  end
      
  resources :calificaciones, :only => :index do
    get :shows, :on => :collection
  end 
  
  resources :home , :only => :index do
    get :alumnos_tabla, :on => :collection    
    get :error, :on => :collection
    get :show_inscripciones, :on => :collection
    get :user_data, :on => :collection
    get :password_change, :on => :collection
    get :save_password, :on => :collection
    post :save_password, :on => :collection
  end
  #  match 'home/alumnos_tabla', :controller => 'alumnos', :action => 'alumnos_tabla'


  resources :users do
    get :editar_datos , :on => :collection
    get :mostrar , :on => :collection
    get :actualizar1 , :on => :collection
  end

  resources :estancias_profesionales , :only => :index do
    get :shows, :on => :collection
	get :download, :on => :collection
	get :download_guia, :on => :collection
	get :show_empresa, :on => :collection
	post :index, :on => :collection
	get :documentos_registrados, :on => :collection
	get :add_empresa, :on => :collection
	get :del_empresa, :on => :collection
	get :send_opcion, :on => :collection
	get :select_opcion, :on => :collection
  end


  resources :adeudos , :only => :index do
    get :shows, :on => :collection
  end
  
  get "restricts/access_denied"


  resources :users do
    get :editar_datos , :on => :collection
    get :mostrar , :on => :collection
    get :actualizar , :on => :collection
  end
  get 'users/actualizar', :controller => 'users', :action => 'actualizar'


  #  resources :home

  resources :user_sessions do 
    get :user_data, :on => :collection
  end
#  get "user_sessions/new", to: "user_sessions#new" , as: :login
#  get "user_sessions/destroy", to: "user_sessions#destroy" , as: :logout




 
  root :to => 'home#index'
    
end

app/views/shared/_array_messages.html.erb
<% unless messages.blank? %>
  <div class="row">
    <div class="col-md-12 col-md-offset-0">
      <div class="alert alert-<%= class_name %> alert-dismissible" role="alert" > 
        <button type="button" class="close" data-dismiss="alert"> 
          <span aria-hiden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>            
        <% messages.each do |msg_title, *msg| %> 
          <h3 class="text-center"> <%= msg_title || "Información" %> </h3>
          <% msg.each do |m| %>
          <p class="text-center"> <%= m %> </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="wrapper_error">
    <% impidio_impidieron = target.errors.count > 1 ? 'impidieron' : 'impidió' %>
    <h2> <%= pluralize(target.errors.count, "error") %> <%= impidio_impidieron %>  que el registro se guardara: </h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div class="row content">
  <% flash.each do |name, msg| %>
  <% if msg.instance_of?(Array) %>
    <%= render :partial => "shared/messages", :locals => { :msg_title => msg.first, :msg => msg[1..-1], :class_name => name } %>
  <% else %>
    <%= render :partial => "shared/messages", :locals => { :msg => msg, :class_name => name } %>
  <% end %>
  <% end %>
</div>
<script type="application/javascript">
    $(document).ready(function() {
        setTimeout(function() {
            $(".content").fadeOut(1500);
        }, 15
    )
    });
</script>

app/views/shared/_header.erb
<!--cabecera de la aplicacion web, logo y nombre del portal-->
<header class="container">
  <div class="row">

    <div class="col-lg-3 col-md-3 col-sm-6">
      <%=  image_tag(("seres-03.png"), :class => "image-seres")%>
    </div>

    <div class="col-lg-3 col-md-3 col-sm-6">
      <p class="text-info portal_alumnos text-left">| Portal de Alumnos</p>
    </div>

    <!--<div class="col-lg-6 col-md-6 col-sm-12">
      <div class="pull-right espacio_botones">
        <%#= link_to user_session_path(current_user) , :class => "btn btn-sm btn-default", method: :delete do %>
          <span class="fa fa-sign-out"></span> <span class="hidden-xs text-user"> Cerrar Sesión</span>
        <%# end %>
      </div>

      <div class="pull-right espacio_botones">
        <%#= link_to user_data_home_index_path() , :class => "btn btn-sm btn-info" do %>
          <span class="glyphicon glyphicon-user"></span>
          <span class="hidden-xs text-user"> <%#= "#{current_user.login.to_s}"%> </span>
        <%#end %>
      </div>
    </div>-->

    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="pull-right espacio_botones">
        <%= link_to user_session_path(current_user) , :class => "btn btn-sm", method: :delete do %>
          <span class="fa fa-sign-out close_icon_header"></span> <span class="hidden-xs close-session"> Cerrar Sesión</span>
        <% end %>
      </div>

      <div class="pull-right espacio_botones">
        <%= link_to root_path, :class => "btn btn-sm"  do %>
          <span class="fa fa-home home_icon_header"></span> <span class="hidden-xs close-session"> Inicio</span>
        <% end %>
      </div>

      <div class="pull-right espacio_botones">
        <%= link_to user_data_home_index_path() , :class => "btn btn-sm" do %>
          <span class="fa fa-user user_icon_header"></span>
          <span class="hidden-xs text-user"><%= capitalize_each_word @usuario.alumno.full_name %> </span>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_admin.html.erb
<!--cabecera de la aplicacion web, logo y nombre del portal-->
<header class="container">
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6">
      <%=  image_tag(("seres-03.png"), :class => "image-seres")%>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6">
      <p class="text-info portal_alumnos text-left">| Portal de Alumnos</p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="pull-right espacio_botones">
        <%= link_to user_session_path(current_user) , :class => "btn btn-sm", :method => :delete do %>
          <span class="fa fa-sign-out close_icon_header"></span> <span class="hidden-xs close-session"> Cerrar Sesión</span>
        <% end %>
      </div>
      <div class="pull-right espacio_botones">
        <%= link_to admin_index_path, :class => "btn btn-sm"  do %>
          <span class="fa fa-home home_icon_header"></span> <span class="hidden-xs close-session"> Inicio</span>
        <% end %>
      </div>
      <div class="pull-right espacio_botones">
        <%= link_to '#', :class => "btn btn-sm" do %>
          <span class="fa fa-user user_icon_header"></span> <span class="hidden-xs text-user"><%= capitalize_each_word @usuario.login %> </span>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_information_messages.html.erb
<% if !mensaje.blank? %>
   <div class="row">
     <div class="container">
       <div class="col-md-6 col-md-offset-3 espacio">
          <div class="alert alert-info alert-dismissable" role="alert">
             <button type="button" class="close" data-dismiss="alert"> 
             <span aria-hiden="true">&times;</span>
             <span class="sr-only">close</span>
             </button>
              <h3 class="text-center"> <%= encabezado || "Información" %> </h3>
              <p class="text-center"> <%= mensaje %> </p>
           </div>
       </div>
     </div>
    </div>
<% end %>

app/views/shared/_messages.html.erb
<% unless msg.blank? %>
  
    <div class="row"> 
      <div class="col-md-6 col-md-offset-3">
        <div class="alert alert-<%= class_name %> alert-dismissible" role="alert" > 
          <button type="button" class="close" data-dismiss="alert"> 
            <span aria-hiden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>          
          <% if defined?(msg_title) && msg_title.present?  %> 
          <h3 class="text-center"> <%= upcase_with_accents(msg_title) %> </h3>
          <% end %>
          <% if msg.instance_of?(Array) %>
          <p class="text-center">
            <% msg.each do |m| %>
              <%= m %> <br/>
            <% end %>
            </p>
          <% else %>
            <p class="text-center"> <%= msg %> </p>
          <% end %>

        </div>
      </div>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
<!--Menú de Navegación-->
<div class="container">
  <div class="row ">
    <div class="btn-group btn-group-justified well_menu">

      <!-- links-->

      <!--<div class="btn-group">
        <%#= link_to(root_path, :class => 'btn btn-nav' + active('home', false, ['user_data', 'show_inscripciones'].include?(params[:action]))) do %>
          <i class="fa fa-home"></i><span class="textos_menu hidden-sm hidden-xs"> Inicio </span>
        <%#end %>
      </div>-->

      <div class="btn-group">
        <%= link_to(horarios_path, :class => 'btn btn-nav' + active('horarios')) do %>
          <i class="fa fa-clock-o"></i><span class="textos_menu hidden-sm hidden-xs"> Horario de Clases </span>
        <% end %>
      </div>

      <div class="btn-group">
        <%= link_to(calificaciones_path, :class => 'btn btn-nav' + active('calificaciones')) do %>
          <i class="fa fa-list-alt"></i><span class="textos_menu hidden-sm hidden-xs"> Calificaciones </span>
        <% end %>
      </div>


      <div class="btn-group">
        <%= link_to(examenes_path, :class => 'btn btn-nav' + active('examenes')) do %>
          <i class="fa fa-calendar-check-o"></i><span class="textos_menu hidden-sm hidden-xs">  Calendario de Exámenes </span>
        <% end %>
      </div>

      <%#*<div class="btn-group">%>
      <%#= link_to(root_path, :class => 'btn btn-nav') do %>
      <%#*<i class="fa fa-pencil"></i><span class="textos_menu hidden-sm hidden-xs"> Solicitud de Exámenes </span>%>
      <%# end %>
      <%#*</div>%>

      <div class="btn-group">
        <%= link_to(adeudos_path, :class => 'btn btn-nav' + active('adeudos') ) do %>
          <i class="fa fa-usd"></i><span class="textos_menu hidden-sm hidden-xs">  Adeudos </span>
        <% end %>
      </div>

      <div class="btn-group">
        <%= link_to(estancias_profesionales_path, :class => 'btn btn-nav' + active('estancias_profesionales')) do %>
          <i class="fa fa-building"></i><span class="textos_menu hidden-sm hidden-xs">  Estancias Profesionales </span>
        <% end %>
      </div>

      <%#   @fecha_verano_inicio_7sem_menu = EstanciasConfig.first.fecha_verano_inicio_7sem
           @fecha_verano_fin_7sem_menu = EstanciasConfig.first.fecha_verano_fin_7sem %>



      <%# if @last_inscripcion.semestre_id.to_s >= '6' ||  @last_inscripcion.semestre_id.to_s == '12'%>
        <%# if @fecha_verano_inicio_7sem_menu && @fecha_verano_fin_7sem_menu%>
          <%# if  Date.today >= @fecha_verano_inicio_7sem_menu  && Date.today <= @fecha_verano_fin_7sem_menu  %>

          <%#end%>
    <%#end %>
    <%#end %>

    </div>
  </div>
</div>

app/views/shared/_navigation_admin.html.erb
<!--Menú de Navegación-->
<div class="container">
  <div class="row ">
    <div class="btn-group btn-group-justified well_menu">
      <div class="btn-group">
        <%= link_to( admin_crear_cuenta_path, :class => 'btn btn-nav' + active('Ver')) do %>
          <i class="fa fa-list-alt"></i><span class="textos_menu hidden-sm hidden-xs"> Crear Cuenta </span>
        <% end %>
      </div>

      <div class="btn-group">
        <%= link_to(admin_reiniciar_cuenta_path, :class => 'btn btn-nav' + active('Editar')) do %>
          <i class="fa fa-list-alt"></i><span class="textos_menu hidden-sm hidden-xs"> Reiniciar Cuenta </span>
        <% end %>
      </div>

      <div class="btn-group">
        <%= link_to(admin_reset_password_path, :class => 'btn btn-nav' + active('Crear')) do %>
          <i class="fa fa-list-alt"></i><span class="textos_menu hidden-sm hidden-xs"> Cambiar Contraseña </span>
        <% end %>
      </div>

    </div>
  </div>
</div>