config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin/crear_cuenta'
  get 'admin/reiniciar_cuenta'
  get 'admin/reset_password'
  post 'admin/setear_datos_del_alumno'
  post 'admin/actualizar_password'

  resources :password_resets, :only => [ :new, :create, :edit, :update ]

  resources :examenes, :only => :index do
    get :shows, :on => :collection
  end

  resources :horarios, :only => :index do
    get :shows, :on => :collection
  end
  
  resources :historiales, :only => :index do
    get :shows, :on => :collection
  end
      
  resources :calificaciones, :only => :index do
    get :shows, :on => :collection
  end 
  
  resources :home , :only => :index do
    get :alumnos_tabla, :on => :collection    
    get :error, :on => :collection
    get :show_inscripciones, :on => :collection
    get :user_data, :on => :collection
    get :password_change, :on => :collection
    get :save_password, :on => :collection
    post :save_password, :on => :collection
  end
  #  match 'home/alumnos_tabla', :controller => 'alumnos', :action => 'alumnos_tabla'


  resources :users do
    get :editar_datos , :on => :collection
    get :mostrar , :on => :collection
    get :actualizar1 , :on => :collection
  end

  resources :estancias_profesionales , :only => :index do
    get :shows, :on => :collection
	get :download, :on => :collection
	get :download_guia, :on => :collection
	get :show_empresa, :on => :collection
	post :index, :on => :collection
	get :documentos_registrados, :on => :collection
	get :add_empresa, :on => :collection
	get :del_empresa, :on => :collection
	get :send_opcion, :on => :collection
	get :select_opcion, :on => :collection
  end


  resources :adeudos , :only => :index do
    get :shows, :on => :collection
  end
  
  get "restricts/access_denied"


  resources :users do
    get :editar_datos , :on => :collection
    get :mostrar , :on => :collection
    get :actualizar , :on => :collection
  end
  get 'users/actualizar', :controller => 'users', :action => 'actualizar'


  #  resources :home

  resources :user_sessions do 
    get :user_data, :on => :collection
  end
#  get "user_sessions/new", to: "user_sessions#new" , as: :login
#  get "user_sessions/destroy", to: "user_sessions#destroy" , as: :logout




 
  root :to => 'home#index'
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_user

  def index
    if current_user.role_id == 1
      @usuario = current_user
    else
      user_data
      @periodo_actual = current_ciclo.ciclo
      @inscripciones = @usuario.alumno.inscripciones.select{|item| item.ciclo_id == current_ciclo.id}
    end
    @universidad = Universidad.first
  end
  
  def show_inscripciones
    user_data
     @usuario = current_user
     @inscripciones = @usuario.alumno.inscripciones
     @inscripciones_agrupadas = @inscripciones.group_by { |inscripcion| inscripcion.semestr.clave_semestre }
  end
  
  def user_data
    @usuario = current_user
    @periodo_actual = current_ciclo.ciclo
    @last_inscripcion = Inscripcion.get_last_user_data(Alumno.find_by_user_id(current_user.id).id)
    @profesor =  @usuario.alumno.profesor || Profesor.new
  end

  def password_change
    @usuario = current_user
    ciclo = Ciclo.get_ciclo_at_fecha(Date.today) || current_ciclo
    @inscripciones = @usuario.alumno.inscripciones.select{|item| item.ciclo_id == ciclo.id} if ciclo.present?
    @last_inscripcion = @inscripciones.sort_by{|i| i.semestr.clave}.last
    @last_inscripcion = @usuario.alumno.inscripciones.sort_by{|i| i.semestr.clave}.last if @last_inscripcion.blank?
  end

  def save_password
    puts "\n\n\n\nIniciando guardado...."
    begin
      User.transaction do
        usuario = User.find(params[:id].to_i)
        @usuario = usuario
        @usuario.role_id = (Role.find_by_name "ALUMNO").id
        @usuario.campus_id = usuario.campus_id
        @usuario.login = usuario.login
        @usuario.email = usuario.email
        @usuario.password = params[:password]
        @usuario.password_confirmation = params[:password_confirmation]
        @periodo_actual = current_ciclo.ciclo
        ciclo = Ciclo.get_ciclo_at_fecha(Date.today) || current_ciclo
        @inscripciones = @usuario.alumno.inscripciones.select{|item| item.ciclo_id == ciclo.id} if ciclo.present?
        @last_inscripcion = @inscripciones.sort_by{|i| i.semestr.clave}.last
        @last_inscripcion = @usuario.alumno.inscripciones.sort_by{|i| i.semestr.clave}.last if @last_inscripcion.blank?
        @profesor =  @usuario.alumno.profesor || Profesor.new
        respond_to do |format|
          if @usuario.save!
            format.html { render :action => 'user_data' }
            flash[:notice] = "Contraseña Actualizada"
          end
        end
      end
    rescue Exception => error
      @usuario = current_user
      ciclo = Ciclo.get_ciclo_at_fecha(Date.today) || current_ciclo
      @inscripciones = @usuario.alumno.inscripciones.select{|item| item.ciclo_id == ciclo.id} if ciclo.present?
      @last_inscripcion = @inscripciones.sort_by{|i| i.semestr.clave}.last
      @last_inscripcion = @usuario.alumno.inscripciones.sort_by{|i| i.semestr.clave}.last if @last_inscripcion.blank?
      flash[:error] = "La contraseña no coincide con la confirmación"
      respond_to do |format|
        format.html { render :action => 'password_change' }
        format.xml  { render :xml => @usuarior.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  
  def get_semester_name(clave)
    case (clave)
    when "PRIMERO", "TERCERO"
      name =  clave.chop
    else
      name = clave
    end
    return name
  end
end

app/views/home/_info_inscripcion.html.erb
<div class="row">
  <div class="col-sm-12 col-md-10  col-md-offset-1 ">
    <div class="table-responsive">
      <table class="table table-user-information table-bordered table-list">
        <thead>
        <th colspan="2"> <%= get_semester_name(inscripcion.semestr.clave_semestre)%> SEMESTRE</th>
        </thead>
        <tbody>
          <tr>
            <th class="info">Carrera: </th>
            <td><%= inscripcion.carrera.nombre_carrera.to_s %></td>
          </tr>

          <tr>
            <th class="info">Periodo Escolar: </th>
            <td> <%= inscripcion.ciclo.ciclo.to_s  %></td>
          </tr>
          <tr>
            <th class="info">Grupo(s): </th>
            <td> <%=  inscripcion.grupo.nombre%> </td>     
          </tr>
          <tr>
            <th class="info">Beca </th>
            <td><%= !inscripcion.beca.nil? ? inscripcion.beca.to_s + "%" : "Sin Beca Asignada" %></td> 
          </tr>
          <%
            cadena = ""
            asignaturas = Curso.select("cursos.id, materias_planes.nombre, materias_planes.orden").
                joins(:inscripciones_cursos, :asignatura).
                where(:inscripciones_cursos => {:inscripcion_id => inscripcion.id}).
                order("materias_planes.orden")

            unless asignaturas.blank?
              asignaturas.each_with_index do |a,index|
                if !(asignaturas.size.to_i-1) == index.to_i
                cadena  = cadena.to_s + a.nombre.to_s + "\n"+ "NC"
                else
                cadena = cadena.to_s + a.nombre.to_s+ " ,"
                end
              end
            else
              cadena = "NO EXISTE REGISTRO DE ASGINATURAS PARA ESTÁ INSCRIPCIÓN"
            end
          %>
          <tr>
            <th class="info">Materias </th>
            <td>
              <div>

              <%= cadena.each_line {|s| p s}%>


              </div>
            </td>
          </tr>


        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="">
  <% if current_user.role_id == 1 %>
    <div class="espacio">
      <div class="well">
        <div class="row">
          <div class="col-lg-12">
            <%=  image_tag("logo_utm-03.jpg",  :class => "img-responsive center-block") %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 espacio_2">
            <h3 class="text-center"><%=@universidad.nombre%></h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <h4 class="text-center ">Departamento de Servicios Escolares</h4>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <% if @usuario %>
      <% if @usuario.alumno.blank?  %>
        <%= render :partial => "shared/messages", :locals => { :msg => "El usuario no esta registrado en el sistema", :class_name => "error" } %>
      <% else %>
        <div class="espacio">
          <div class="well">
            <div class="row">
              <div class="col-lg-12">
                <%=  image_tag("logo_utm-03.jpg",  :class => "img-responsive center-block") %>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12 espacio_2">
                <h3 class="text-center"><%=@universidad.nombre%></h3>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <h4 class="text-center ">Departamento de Servicios Escolares</h4>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= link_to "Página de Ingreso", new_user_session_path %>
    <% end %>
  <% end %>
</div>

app/views/home/password_change.html.erb
<div class="">
  <% if @usuario %>
    <% if @usuario.alumno.blank?  %>
      <%= render :partial => "shared/messages", :locals => { :msg => "El usuario no esta registrado en el sistema", :class_name => "error" } %>
    <% else %>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2  col-lg-6 col-lg-offset-3 espacio">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Cambiar Contraseña</h4>
            </div>
            <%= form_tag(:action => "save_password", :controller => "home") do %>
              <div class="panel-body">
                <div class="foto center-block">
                  <i class="glyphicon glyphicon-user"></i>
                </div>
                <div class="row">
                  <div class="col-sm-12 col-md-10  col-md-offset-1 ">
                    <div class="table-responsive">
                      <table class="table table-user-information table-bordered table-list">
                        <tbody>
                        <tr>
                          <th class="info">Usuario: </th>
                          <td> <%= label_tag :name, @usuario.login, class: "form-label" %> </td>
                          <%= hidden_field_tag :id,  @usuario.id %>
                        </tr>
                        <tr>
                          <th class="info">Contraseña: </th>
                          <td>
                            <%= password_field_tag :password, "", placeholder: 'Nueva contraseña', class: "form-control", autocomplete: "off" %>
                          </td>
                        </tr>
                        <tr>
                          <th class="info">Confirmación de Contraseña:</th>
                          <td>
                            <%= password_field_tag :password_confirmation, "", placeholder: 'Confirmar Nueva contraseña', class: "form-control", autocomplete: "off" %>
                          </td>
                        </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <div class="panel-footer">
                <div class="text-center">
                  <%= button_tag(type: "submit" , data: { confirm: '¿Está seguro que desea guardar los cambios?'}, class: 'tag-tooltip', title: 'Se recomienda usar una contraseña segura que no uses para ningún otro sitio', 'data-toggle' => 'tooltip', 'data-placement' => 'right' , disable_with: "Guardando", class: "btn btn-primary") do %>
                    <span class="glyphicon glyphicon-save"></span> Guardar
                  <% end %>

                  <%= link_to(user_data_home_index_path, class: "btn btn-danger") do %>
                    <span class="fa fa-close"></span> Cancelar
                  <% end %>
                </div>
                <div class="text-center">

                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/home/show_inscripciones.html.erb
<% unless @inscripciones_agrupadas.blank? %>
  <!--panel inscripciones agrupadas-->
  <div class="row">

    <div class="col-md-12 espacio">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <div class="col-lg-2">
              <h4>Inscripciones</h4>
            </div>

            <div class="col-lg-10">
              <span class="pull-right">
                <!-- Tabs -->
                <ul class="nav panel-tabs">
                  <% @inscripciones_agrupadas.each do |clave, inscripciones| %>
                    <li class="<%=  clave=="PRIMERO" ? 'active' : 'other' %>"> <a href="#inscripcion<%= clave %>" data-toggle="tab"> <%= capitalize_with_accents(clave) %> </a></li>
                  <% end %>
                </ul>
              </span>
            </div>
          </div>
        </div>

        <div class="panel-body">
          <div class="tab-content">
            <% @inscripciones_agrupadas.each do |clave, inscripciones|%>
            <div class="tab-pane  <%=  clave=="PRIMERO" ? 'active' : 'other' %>" id="inscripcion<%= clave %>">
              <% inscripciones.each do  |inscripcion| %>
                <%= render 'info_inscripcion' , :inscripcion => inscripcion%>
              <% end %>
            </div>
            <%end%>     
          </div>
        </div>
      </div>
    </div>
  </div>              

<% else %>
  <%= render :partial => "shared/messages", :locals => { :msg => 'No te has inscrito en algun periodo.', :class_name => 'danger' } %>
<% end %>

app/views/home/user_data.html.erb
<div class="">

  <% if @usuario %>
    <% if @usuario.alumno.blank?  %>
      <%= render :partial => "shared/messages", :locals => { :msg => "El usuario no esta registrado en el sistema", :class_name => "error" } %>
    <% else %>


      <div class="row">
        <div class="col-sm-8 col-sm-offset-2  col-lg-6 col-lg-offset-3 espacio">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4>Información del Usuario</h4>
            </div>

            <div class="panel-body">
              <div class="foto center-block">
                <i class="glyphicon glyphicon-user"></i>
              </div>

              <div class="row">
                <div class="col-sm-12 col-md-10  col-md-offset-1 ">
                  <div class="table-responsive">
                    <table class="table table-user-information table-bordered table-list">
                      <tbody>
                        <tr>
                          <th class="info">Nombre del Alumno:</th>
                          <td><%= capitalize_each_word @usuario.alumno.full_name %></td>
                        </tr>

                        <tr>
                          <th class="info">Matrícula:</th>
                          <td><%= @usuario.alumno.matricula %></td>
                        </tr>

                        <tr>
                          <th class="info">Carrera:</th>
                          <td><%= capitalize_each_word  @usuario.alumno.get_nombre_carrera %></td>
                        </tr>
                        <% if @last_inscripcion.present? %>
                          <tr>
                            <th class="info">Grupo Actual:</th>
                            <td><%=  Grupo.find(@last_inscripcion[:grupo_id]).nombre %> </td>
                          </tr>

                          <tr>
                            <th class="info">Periodo Escolar:</th>
                            <td><%= @last_inscripcion[:ciclo] %> </td>
                          </tr>

                          <tr>
                            <th class="info">Beca:</th>
                            <td><%= !@last_inscripcion[:beca].nil? ? @last_inscripcion[:beca].to_s + "%" : "Sin Beca Asignada"%></td>
                          </tr>
                        <% end %>
                        <tr>
                          <th class="info">Número de Seguro Social:</th>
                          <td><%= @usuario.alumno.nss.to_s %></td>
                        </tr>
                        <tr>
                          <th class="info">Tutor Profesor:</th>
                          <td><%= @profesor.full_name %></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            </div>
            <div class="panel-footer">
             <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-12">
                <div class='text-right'><%= link_to 'Cambiar Contraseña', password_change_home_index_path, :class => "btn btn-info"%></div>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-12">
                <div class='text-left'><%= link_to 'Ver todas las Inscripciones', show_inscripciones_home_index_path , :class => "btn btn-info"%></div>
              </div>
             </div>
            </div>

          </div>
        </div>
      </div>  
    <% end %>
  <% else %>
    <%= link_to "Página de Ingreso", new_user_session_path %>
  <% end %>



</div>